version: '3.8'
services:
  frontend:
    image: node:20
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
    command: sh -c "npm install && yes | npx shadcn@latest add card label input button && npm run dev"

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
